AllCops:
  Exclude:
    - 'lib/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/swagger_helper.rb'
    - 'Guardfile'
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/LineLength:
  IgnoredPatterns: ['\A#']
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
    - 'db/*'
Style/HashSyntax:
  Exclude:
    - 'spec/**/*'
