version: '3.3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "54320:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres:
